#pragma once
#include <cstddef>

// Embedded word list: ~470 common English words, lowercase ASCII.
// Edit the list, not the code around it.
inline constexpr const wchar_t* kWords[] = {
    L"the", L"be", L"to", L"of", L"and", L"a", L"in", L"that", L"have", L"it",
    L"for", L"not", L"on", L"with", L"he", L"as", L"you", L"do", L"at", L"this",
    L"but", L"his", L"by", L"from", L"they", L"we", L"say", L"her", L"she", L"or",
    L"an", L"will", L"my", L"one", L"all", L"would", L"there", L"their", L"what", L"so",
    L"up", L"out", L"if", L"about", L"who", L"get", L"which", L"go", L"me", L"when",
    L"make", L"can", L"like", L"time", L"no", L"just", L"him", L"know", L"take", L"people",
    L"into", L"year", L"your", L"good", L"some", L"could", L"them", L"see", L"other", L"than",
    L"then", L"now", L"look", L"only", L"come", L"its", L"over", L"think", L"also", L"back",
    L"after", L"use", L"two", L"how", L"our", L"work", L"first", L"well", L"way", L"even",
    L"new", L"want", L"because", L"any", L"these", L"give", L"day", L"most", L"us", L"is",
    L"was", L"are", L"been", L"has", L"had", L"were", L"said", L"each", L"did", L"may",
    L"such", L"where", L"much", L"before", L"right", L"too", L"old", L"same", L"tell", L"why",
    L"man", L"woman", L"child", L"world", L"school", L"state", L"family", L"student", L"group", L"country",
    L"problem", L"hand", L"part", L"place", L"case", L"week", L"company", L"system", L"program", L"question",
    L"government", L"number", L"night", L"point", L"home", L"water", L"room", L"mother", L"area", L"money",
    L"story", L"fact", L"month", L"lot", L"study", L"book", L"eye", L"job", L"word", L"business",
    L"issue", L"side", L"kind", L"head", L"house", L"service", L"friend", L"father", L"power", L"hour",
    L"game", L"line", L"end", L"member", L"law", L"car", L"city", L"community", L"name", L"president",
    L"team", L"minute", L"idea", L"kid", L"body", L"information", L"parent", L"face", L"others", L"level",
    L"office", L"door", L"health", L"person", L"art", L"war", L"history", L"party", L"result", L"change",
    L"morning", L"reason", L"research", L"girl", L"guy", L"moment", L"air", L"teacher", L"force", L"education",
    L"foot", L"boy", L"age", L"policy", L"music", L"market", L"sense", L"nation", L"plan", L"college",
    L"interest", L"death", L"course", L"someone", L"experience", L"effect", L"class", L"control", L"care", L"field",
    L"development", L"role", L"effort", L"rate", L"heart", L"show", L"leader", L"light", L"voice", L"wife",
    L"police", L"mind", L"price", L"report", L"decision", L"son", L"view", L"relationship", L"town", L"road",
    L"arm", L"difference", L"value", L"building", L"action", L"model", L"season", L"society", L"tax", L"director",
    L"position", L"player", L"record", L"paper", L"space", L"ground", L"form", L"event", L"matter", L"center",
    L"couple", L"site", L"project", L"activity", L"star", L"table", L"need", L"court", L"oil", L"situation",
    L"cost", L"industry", L"figure", L"street", L"image", L"phone", L"data", L"picture", L"practice", L"piece",
    L"leave", L"put", L"mean", L"keep", L"let", L"begin", L"seem", L"help", L"talk", L"turn",
    L"start", L"might", L"hear", L"play", L"run", L"move", L"live", L"believe", L"hold", L"bring",
    L"happen", L"must", L"write", L"provide", L"sit", L"stand", L"lose", L"pay", L"meet", L"include",
    L"continue", L"set", L"learn", L"lead", L"understand", L"watch", L"follow", L"stop", L"create", L"speak",
    L"read", L"allow", L"add", L"spend", L"grow", L"open", L"walk", L"win", L"offer", L"remember",
    L"love", L"consider", L"appear", L"buy", L"wait", L"serve", L"die", L"send", L"expect", L"build",
    L"stay", L"fall", L"cut", L"reach", L"kill", L"remain", L"suggest", L"raise", L"pass", L"sell",
    L"require", L"decide", L"pull", L"return", L"explain", L"hope", L"develop", L"carry", L"break", L"receive",
    L"agree", L"support", L"hit", L"produce", L"eat", L"cover", L"catch", L"draw", L"choose", L"cause",
    L"listen", L"wonder", L"great", L"little", L"own", L"big", L"high", L"different", L"small", L"large",
    L"next", L"early", L"young", L"important", L"few", L"public", L"bad", L"able", L"free", L"sure",
    L"better", L"true", L"whole", L"clear", L"easy", L"strong", L"special", L"hard", L"possible", L"late",
    L"real", L"best", L"low", L"black", L"white", L"certain", L"full", L"short", L"single", L"second",
    L"again", L"against", L"always", L"around", L"away", L"between", L"both", L"during", L"either", L"enough",
    L"ever", L"every", L"far", L"here", L"least", L"less", L"many", L"never", L"often", L"once",
    L"quite", L"rather", L"really", L"since", L"still", L"together", L"under", L"until", L"very", L"while",
    L"yet", L"today", L"later", L"almost", L"already", L"along", L"among", L"maybe", L"perhaps", L"however",
    L"without", L"within", L"though", L"through", L"toward", L"across", L"behind", L"call", L"become", L"feel",
    L"try", L"ask", L"find", L"long", L"down", L"thing", L"life",
};
inline constexpr size_t kWordCount = sizeof(kWords) / sizeof(kWords[0]);
